### ISSUE TITLE
docker server failing with a Runtime error

### ISSUE THREAD

**Issue by idcrook** [Kapeli/Dash-Annotations#10]
Using the instructions provided in the README for docker, I am getting the following HTTP/1.1 500 Internal Server Error error (stacktrace below).  I am able to make requests through NGINX gateway, but am unable to successfully retrieve any resource from the docker container webserver.  Any suggestions?

== BEGIN OF ERROR OUTPUT PAGE === 
Whoops, looks like something went wrong.

**1/1**
RuntimeException in EncryptionServiceProvider.php line 29:
No supported encrypter found. The cipher and / or key length are invalid.

```
in EncryptionServiceProvider.php line 29
at EncryptionServiceProvider->Illuminate\Encryption\{closure}(object(Application), array()) in Container.php line 733
at Container->build(object(Closure), array()) in Container.php line 626
at Container->make('encrypter', array()) in Application.php line 432
at Application->make('encrypter') in Application.php line 807
at Application->loadComponent('app', 'Illuminate\Encryption\EncryptionServiceProvider', 'encrypter') in Application.php line 562
at Application->Laravel\Lumen\{closure}(object(Application), array()) in Container.php line 733
at Container->build(object(Closure), array()) in Container.php line 626
at Container->make('Illuminate\Contracts\Encryption\Encrypter', array()) in Application.php line 432
at Application->make('Illuminate\Contracts\Encryption\Encrypter') in Container.php line 837
at Container->resolveClass(object(ReflectionParameter)) in Container.php line 800
at Container->getDependencies(array(object(ReflectionParameter)), array()) in Container.php line 771
at Container->build('Illuminate\Cookie\Middleware\EncryptCookies', array()) in Container.php line 626
at Container->make('Illuminate\Cookie\Middleware\EncryptCookies', array()) in Application.php line 432
at Application->make('Illuminate\Cookie\Middleware\EncryptCookies') in Pipeline.php line 123
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))
at call_user_func(object(Closure), object(Request)) in Pipeline.php line 103
at Pipeline->then(object(Closure)) in Application.php line 1411
at Application->sendThroughPipeline(array('Illuminate\Cookie\Middleware\EncryptCookies', 'Illuminate\Session\Middleware\StartSession'), object(Closure)) in Application.php line 1185
at Application->dispatch(null) in Application.php line 1125
at Application->run() in index.php line 28
```

**Comment by Kapeli** [comment]
@SolidNerd any idea?

**Comment by solidnerd** [comment]
Did you set the env APP_KEY ? I guess that should be needed here.

**Comment by idcrook** [comment]
I had set it in the docker-compose.yaml, yes...

**Comment by solidnerd** [comment]
Sorry for the late response, i try it by my self and it works for me.

Here is my test docker-compose.yml

```
db:
  image: mariadb
  environment:
    - MYSQL_ROOT_PASSWORD=dash
    - MYSQL_USER=dash
    - MYSQL_PASSWORD=dash
    - MYSQL_DATABASE=annotations
dash:
  build: .
  links:
    - db:db
  ports:
    - "127.0.0.1:9002:9000"
  environment:
    - TOKEN=YourTokenFromGithub
    - DB_USER=dash
    - DB_PASSWORD=dash
    - DB_DATABASE=annotations
    - APP_KEY=someRandomKey
```

My Steps were: 
1. Edit docker-compose.yml
2. docker-compose build
3. docker-compose up

**Comment by idcrook** [comment]
I reran using yours as template (and kept your APP_KEY). My previous had value from a SHASUM of some file.
Got the same error message again... So not sure.  This is not mission critical for me-- I was just hoping to deploy under docker.  Using Ubuntu 14.04 LTS, and more system details for posterity...

```
dpc@vader: ~ $ uname -a
Linux vader 3.13.0-74-generic #118-Ubuntu SMP Thu Dec 17 22:52:10 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
dpc@vader: ~ $ docker -v
Docker version 1.9.1, build a34a1d5
dpc@vader: ~ $ docker-compose -v
docker-compose version 1.5.2, build 7240ff3
```

**Comment by idcrook** [comment]
I am assuming your Dockerfile is this same as this one too?

 https://github.com/Kapeli/Dash-Annotations/blob/master/Dockerfile

**Comment by solidnerd** [comment]
Yep. I pulled the repo again.

**Comment by idcrook** [comment]
I am closing this issue.  Never did get it working, and do not have time to try at the moment.

**Comment by meengit** [comment]
Hi @idcrook, I also discovered this issue. During my search for a solution, [I found a thread](https://laravel.io/forum/06-09-2015-no-supported-encrypter-found-the-cipher-and-or-key-length-are-invalid) about the length of the `cipher` in `laravel`. As far as I understand, it expects 32 characters. 

Setting my `API_KEY` to a length of 32 characters and running `docker-compose up -d --build --force` fixed the error.

```yaml
dash:
  build: .
  links:
    - db:db
  ports:
    - "127.0.0.1:9002:9000"
  environment:
    - TOKEN=MySecretToken 
    - DB_USER=dash
    - DB_PASSWORD=dash
    - DB_DATABASE=annotations
    - DB_HOST=db
    - APP_KEY=MyApiKeyOf32CharactersAbcdefgh32
```
